version: 2
updates:
  - package-ecosystem: "gradle"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "sunday"
      time: "09:00"
    assignees:
      - "wolfieboy09"
    labels:
      - "dependencies"
    commit-message:
      prefix: "[deps] "
    groups:
      gradle-dependencies:
        patterns:
          - "*"
    open-pull-requests-limit: 1
    ignore:
      - dependency-name: "net.neoforged:neoforge"
        update-types: ["version-update:semver-major"]
      - dependency-name: "dev.latvian.mods:kubejs-neoforge"
        update-types: ["version-update:semver-major"]
