modLoader="javafml"
loaderVersion="${loader_version_range}"
license="${mod_license}"
issueTrackerURL="https://github.com/wolfieboy09/ResearchTree/issues"

[[mods]]
modId="researchtree"
version="${mod_version}"
displayName="${mod_name}"
#updateJSONURL="https://change.me.example.invalid/updates.json"
#displayURL="https://change.me.to.your.mods.homepage.example.invalid/"
logoFile="icon.png"
#credits=""
authors="${mod_authors}"
description='''${mod_description}'''

[[mixins]]
config="researchtree.mixins.json"

[[dependencies.researchtree]]
    modId="neoforge"
    type="required"
    versionRange="[${neo_version},)"
    ordering="NONE"
    side="BOTH"

[[dependencies.researchtree]]
    modId="minecraft"
    type="required"
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="BOTH"

[[dependencies.researchtree]]
    modId="kubejs"
    type="optional"
    versionRange="[${kubejs_version},)"
    ordering="NONE"
    side="BOTH"